---
title: "Kiki Takeuchi"
output: html_document
---
*****


### Education
**UC Santa Barbara**, *Undergraduate*

Expected Graduation: June 2021

Environmental Studies B.S.


**Las Lomas High School**
Graduated June 2017

*****

### Experience

**Wildlands Studies**, *Research Student*

Wildlands Program - Thailand, Indonesia

January 2020- March 2020

- 6-week study abroad environmental research program in Thailand and Indonesia
- Skills learned included underwater transects, photo replication sites, writing research papers, and species identification

**Server**
Burma 2 - Walnut Creek, CA

July 2019 - January 2020

**Marketing Intern** 
Touch A Heart - Oahu, HI

June 2018 - August 2018

*****

### Technical Skills
- Competent in Microsoft Word, Excel Spreadsheets, Canva Marketing Tools, Basic Wordpress skills, Keynote
- Competent in Aloha Restaurant POS System
- Research skills: species identification of coral reef fish species, GIS exposure, transects on land and in water, photo replication sites, underwater photography
- Open Water Dive Certified
- Competent in ArcGIS